// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv.proto

package com.klose.hash.mapreduce;

public final class KeyValue {
  private KeyValue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class KVList extends
      com.google.protobuf.GeneratedMessage {
    // Use KVList.newBuilder() to construct.
    private KVList() {
      initFields();
    }
    private KVList(boolean noInit) {}
    
    private static final KVList defaultInstance;
    public static KVList getDefaultInstance() {
      return defaultInstance;
    }
    
    public KVList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.klose.hash.mapreduce.KeyValue.internal_static_cn_ict_cacuts_mapreduce_KVList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.klose.hash.mapreduce.KeyValue.internal_static_cn_ict_cacuts_mapreduce_KVList_fieldAccessorTable;
    }
    
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // repeated bytes vlist = 2;
    public static final int VLIST_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> vlist_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getVlistList() {
      return vlist_;
    }
    public int getVlistCount() { return vlist_.size(); }
    public com.google.protobuf.ByteString getVlist(int index) {
      return vlist_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      for (com.google.protobuf.ByteString element : getVlistList()) {
        output.writeBytes(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getVlistList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getVlistList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.klose.hash.mapreduce.KeyValue.KVList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.klose.hash.mapreduce.KeyValue.KVList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.klose.hash.mapreduce.KeyValue.KVList result;
      
      // Construct using com.klose.hash.mapreduce.KeyValue.KVList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.klose.hash.mapreduce.KeyValue.KVList();
        return builder;
      }
      
      protected com.klose.hash.mapreduce.KeyValue.KVList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.klose.hash.mapreduce.KeyValue.KVList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.klose.hash.mapreduce.KeyValue.KVList.getDescriptor();
      }
      
      public com.klose.hash.mapreduce.KeyValue.KVList getDefaultInstanceForType() {
        return com.klose.hash.mapreduce.KeyValue.KVList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.klose.hash.mapreduce.KeyValue.KVList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.klose.hash.mapreduce.KeyValue.KVList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.klose.hash.mapreduce.KeyValue.KVList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.vlist_ != java.util.Collections.EMPTY_LIST) {
          result.vlist_ =
            java.util.Collections.unmodifiableList(result.vlist_);
        }
        com.klose.hash.mapreduce.KeyValue.KVList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.klose.hash.mapreduce.KeyValue.KVList) {
          return mergeFrom((com.klose.hash.mapreduce.KeyValue.KVList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.klose.hash.mapreduce.KeyValue.KVList other) {
        if (other == com.klose.hash.mapreduce.KeyValue.KVList.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.vlist_.isEmpty()) {
          if (result.vlist_.isEmpty()) {
            result.vlist_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.vlist_.addAll(other.vlist_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              addVlist(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated bytes vlist = 2;
      public java.util.List<com.google.protobuf.ByteString> getVlistList() {
        return java.util.Collections.unmodifiableList(result.vlist_);
      }
      public int getVlistCount() {
        return result.getVlistCount();
      }
      public com.google.protobuf.ByteString getVlist(int index) {
        return result.getVlist(index);
      }
      public Builder setVlist(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.vlist_.set(index, value);
        return this;
      }
      public Builder addVlist(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.vlist_.isEmpty()) {
          result.vlist_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.vlist_.add(value);
        return this;
      }
      public Builder addAllVlist(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.vlist_.isEmpty()) {
          result.vlist_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.vlist_);
        return this;
      }
      public Builder clearVlist() {
        result.vlist_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.ict.cacuts.mapreduce.KVList)
    }
    
    static {
      defaultInstance = new KVList(true);
      com.klose.hash.mapreduce.KeyValue.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.ict.cacuts.mapreduce.KVList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ict_cacuts_mapreduce_KVList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_ict_cacuts_mapreduce_KVList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010kv.proto\022\027cn.ict.cacuts.mapreduce\"$\n\006K" +
      "VList\022\013\n\003key\030\001 \002(\t\022\r\n\005vlist\030\002 \003(\014B$\n\030com" +
      ".klose.hash.mapreduceB\010KeyValue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_ict_cacuts_mapreduce_KVList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_ict_cacuts_mapreduce_KVList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_ict_cacuts_mapreduce_KVList_descriptor,
              new java.lang.String[] { "Key", "Vlist", },
              com.klose.hash.mapreduce.KeyValue.KVList.class,
              com.klose.hash.mapreduce.KeyValue.KVList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
